### ISSUE TITLE
Uhmhn map.inc

### ISSUE THREAD

**Issue by k0ZER** [Southclaws/samp-ini#4]
So basically im trying to compile your scavange and survive gamemode, and it says this:

> C:\Users\Matas.DESKTOP-LGK3FU9\Desktop\uRPG\pawno\include\ini.inc(15) : fatal error 100: cannot read from file: "map"
> 
> Compilation aborted.Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase
> 
> 
> 1 Error.
>  

When i go and edit ini.inc it has included map.inc, but i dont have it, and dont know where to get it.

**Comment by Southclaws** [comment]
Check pawn.json for all dependencies, if you use [sampctl](http://sampctl.com) they will be set up automatically.
